Project Name: ""
Scenes:
  - Scene 1:
      Models:
        - bunny0:
            Transform:
              position:
                - 0
                - -1
                - 0
              rotation:
                - 0
                - 0
                - 0
              scale:
                - 1
                - 1
                - 1
            Material:
              ambient:
                - 0.1
                - 0.1
                - 0.1
              diffuse:
                - 0.8
                - 0.8
                - 0.8
              specular:
                - 0.5
                - 0.5
                - 0.5
              shininess: 32
            Model:
              model_path: bunny.obj
        - bunny1:
            Transform:
              position:
                - -2
                - -1
                - -3
              rotation:
                - 0
                - 0
                - 0
              scale:
                - 1
                - 1
                - 1
            Material:
              ambient:
                - 0.1
                - 0.1
                - 0.1
              diffuse:
                - 0.8
                - 0.8
                - 0.8
              specular:
                - 0.5
                - 0.5
                - 0.5
              shininess: 32
            Model:
              model_path: bunny.obj
        - bunny2:
            Transform:
              position:
                - 2
                - -1
                - -3
              rotation:
                - 0
                - 0
                - 0
              scale:
                - 1
                - 1
                - 1
            Material:
              ambient:
                - 0.1
                - 0.1
                - 0.1
              diffuse:
                - 0.8
                - 0.8
                - 0.8
              specular:
                - 0.5
                - 0.5
                - 0.5
              shininess: 32
            Model:
              model_path: bunny.obj
      Lights:
        - "":
            Transform:
              position:
                - 0
                - 0
                - 3
              rotation:
                - 0
                - 0
                - 0
              scale:
                - 0
                - 0
                - 0
            Light:
              color:
                - 0.5
                - 0.5
                - 0.5
              intensity: 1
        - "":
            Transform:
              position:
                - 0
                - 3
                - 0
              rotation:
                - 0
                - 0
                - 0
              scale:
                - 0
                - 0
                - 0
            Light:
              color:
                - 0.2
                - 0.2
                - 0.2
              intensity: 1
      Cameras:
        Camera Name:
          fovy: 45
          aspect: 1.7777778
          center:
            - 0
            - 0
            - 0
          eye:
            - 0
            - 0
            - 4
          up:
            - 0
            - 1
            - 0