Project Name: Name
Scenes:
  - "":
      Models:
        bunny0:
          Transform:
            position:
              - 0
              - 0
              - 0
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 1
              - 1
              - 1
          Material:
            ambient:
              - 0.1
              - 0.1
              - 0.1
            diffuse:
              - 0.8
              - 0.8
              - 0.8
            specular:
              - 1
              - 0
              - 0
            shininess: 32
          Model:
            model_path: ../resources/models/bunny.obj
        bunny1:
          Transform:
            position:
              - -2
              - -1
              - -3
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 1
              - 1
              - 1
          Material:
            ambient:
              - 0.1
              - 0.1
              - 0.1
            diffuse:
              - 0.8
              - 0.8
              - 0.8
            specular:
              - 1
              - 0
              - 0
            shininess: 32
          Model:
            model_path: ../resources/models/bunny.obj
        bunny2:
          Transform:
            position:
              - 2
              - -1
              - -3
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 1
              - 1
              - 1
          Material:
            ambient:
              - 0.1
              - 0.1
              - 0.1
            diffuse:
              - 0.8
              - 0.8
              - 0.8
            specular:
              - 1
              - 0
              - 0
            shininess: 32
          Model:
            model_path: ../resources/models/bunny.obj
      Lights:
        "":
          Transform:
            position:
              - 0
              - 3
              - 0
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 0
              - 0
              - 0
          Light:
            color:
              - 0.2
              - 0.2
              - 0.2
            intensity: 1