Project Name: project
Scenes:
  - Scene 1:
      Models:
        bunny0:
          Transform:
            position:
              - 0
              - -15.184565
              - 0
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 1
              - 1
              - 1
          Material:
            ambient:
              - 0.1
              - 0.1
              - 0.1
            diffuse:
              - 0.8
              - 0.8
              - 0.8
            specular:
              - 0.5
              - 0.5
              - 0.5
            shininess: 32
          Model:
            model_path: ../resources/models/sphere.obj
        bunny1:
          Transform:
            position:
              - -2
              - -15.184565
              - -3
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 1
              - 1
              - 1
          Material:
            ambient:
              - 0.1
              - 0.1
              - 0.1
            diffuse:
              - 0.8
              - 0.8
              - 0.8
            specular:
              - 0.5
              - 0.5
              - 0.5
            shininess: 32
          Model:
            model_path: ../resources/models/sphere.obj
        bunny2:
          Transform:
            position:
              - 2
              - -15.184565
              - -3
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 1
              - 1
              - 1
          Material:
            ambient:
              - 0.1
              - 0.1
              - 0.1
            diffuse:
              - 0.8
              - 0.8
              - 0.8
            specular:
              - 0.5
              - 0.5
              - 0.5
            shininess: 32
          Model:
            model_path: ../resources/models/sphere.obj
        plane:
          Transform:
            position:
              - 0
              - -1.25
              - 0
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 1
              - 1
              - 1

      Lights:
        - brightLight:
            Transform:
              position:
                - 0.1
                - 0.2
                - 3.5
              rotation:
                - 0
                - 0
                - 0
              scale:
                - 0
                - 0
                - 0
            Light:
              color:
                - 0.9142045
                - 1
                - 0.1805054
              intensity: 1.2
        - light3:
            Transform:
              position:
                - 0.2
                - 0.1
                - -5.5
              rotation:
                - 0
                - 0
                - 0
              scale:
                - 0
                - 0
                - 0
            Light:
              color:
                - 0.3
                - 0
                - 0.2
              intensity: 1.1
      Cameras:
        Camera0:
          fovy: 50
          aspect: 2.1253731
          center:
            - 7.3577985e-07
            - 0.05981063
            - 7.358151e-07
          eye:
            - -4.9
            - 1.8
            - 9.7
        Camera1:
          fovy: 50
          aspect: 1.7777778
          center:
            - 0.0007596521
            - -0.0012175122
            - -0.00059763767
          eye:
            - -7
            - 10
            - 10
        Camera2:
          fovy: 50
          aspect: 1.7777778
          center:
            - 8.7602595e-05
            - 0.00010637142
            - 8.760259e-05
          eye:
            - -7
            - 9
            - 5